### ISSUE TITLE
Client 2.1 Implementation

### ISSUE THREAD

**Issue by jatsrt** [apollographql/reason-apollo#61] opened 2018-03-26 16:53 UTC
With ReactApollo 2.1 release, the main client is now very much usable for ReasonReact. 

```
<Query/>
<Mutation/>
```

What is this projects desire to move to that implementation?
I took some time this morning to POC what this might look like.  I started it as a new project at:
https://github.com/zenlist/bs-react-apollo

I used this project as a starting point(code is not currently properly credited). 

So, the issues/questions.  
Is this worth continuing?
Is there already an effort underway by this community?
Should this be done as a branch to this project or kept separate?

**Comment by jatsrt** [comment] 2018-03-26 17:01
Also to note, I took the approach of just defining the JS interop for the react-apollo components and not "wrapping" with nicer interfaces.

**Comment by kgoggin** [comment] 2018-03-26 18:07
I had the same idea when I saw the 2.1 announcement! For someone who needs some of the advanced features that work out of the box with react-apollo, a straight binding to that library seems like a great idea, and much more doable with the new API. Possibly there are some advantages to a straight Reason implementation of the client (though I'm not sure offhand what they would be?) and so it'd make sense to have both approaches available? I'm definitely interested to hear what the maintainers of this lib think, but even if they want to keep moving in the same direction I'm really interested in working on the alternative approach you've got started.

**Comment by jbaxleyiii** [comment] 2018-03-26 18:17
I'm 100% on board with this and am happy to mentor anyone who wants to take it!

**Comment by jatsrt** [comment] 2018-03-26 19:02
Good news, I migrated all the queries in an app that was using reason-apollo to use my implementation, very little code change and it works.  Now to try to mutations.

**Comment by grsabreu** [comment] 2018-03-27 02:36
This sounds great @jatsrt, the nicest part is that we get the optimistic updates for free with this approach

**Comment by grsabreu** [comment] 2018-03-27 02:38
I think this could get more Reason-idiomatic if we converted them to a single variant before giving back to the Reason code https://github.com/zenlist/bs-react-apollo/blob/develop/src/ReactApollo.re#L33

**Comment by grsabreu** [comment] 2018-03-27 02:39
Will also make this stale https://github.com/apollographql/reason-apollo/pull/39

**Comment by grsabreu** [comment] 2018-03-27 04:08
I think we can even make the API shorter with an usage like:

```reason
module CountQuery = [%graphql
  {|
    query films {
      allFilms {
        totalCount
      }
    }
|}
];

module FilmsQuery = ReactApollo.CreateQuery(CountQuery);

let make = _children => {
  ...component,
  render: _self =>
    <FilmsQuery>
      ...(
           ({data}) =>
             <div>
               <h1> ("Star Wars 2: " |> ReasonReact.stringToElement) </h1>
               {
                 switch (data) {
                   | NoData
                   | Error(_) =>
                   ReasonReact.stringToElement("Something went wrong")
                   | Loading => ReasonReact.stringToElement("Loading")
                   | Data(result) =>
                   switch (result##allFilms) {
                     | None => "No Fils" |> ReasonReact.stringToElement
                     | Some(films) =>
                     "Films Found: "
                     ++ (films##totalCount |> int_from_opt |> string_of_int)
                     |> ReasonReact.stringToElement
                     }
                 }
               }
             </div>
         )
    </FilmsQuery>,
};
```

I forked @jatsrt's work and did a quick implementation of this idea https://github.com/grsabreu/bs-react-apollo/blob/develop/src/CreateQuery.re

**Comment by Gregoirevda** [comment] 2018-03-27 09:57
@jatsrt Totally agree we can now simply bind to the react-apollo components! 
I just think we should just add what @grsabreu wrote: https://github.com/grsabreu/bs-react-apollo/blob/develop/src/CreateQuery.re#L45

**Comment by osener** [comment] 2018-03-27 12:08
I really like where this is going! 

I'd like to point out that there are additional legal states such as `{ data: TData, loading: true }` and `{ data: TData, error: ApolloError }`, and not encoding these in the variants would limit the user interfaces we can model with the `Query` component.

With props `notifyOnNetworkStatusChange` or `errorPolicy="all"` passed to the `Query` component, Apollo allows you to keep displaying the data alongside the loading or error states.

https://www.apollographql.com/docs/react/essentials/queries.html#loading

**Comment by grsabreu** [comment] 2018-03-27 12:18
good point @osener, maybe we could add two more constructors for those states such as `DataWithError(Config.t, apolloError)` and `DataWithLoading(Config.t)`

**Comment by jatsrt** [comment] 2018-03-27 12:26
Wow, ok, so this took off overnight!  I agree with @osener.  Mutation also has "called".  How do we get as close to a pure implementation that does not strip away any functionality while at the same time "reason"ing things up.  @grsabreu you are more knowledgable at this point that I am, so any suggestions super welcome.  

I have bs-react-apollo working in a someone non-simple app, uses many queries, that dynamically update, and mutations that are repetitive and one-off.  Everything you see now in the code is because I needed it for something.  

```
 type data =
    | Loading
    | Error(apolloError)
    | Data(Config.t)
    | NoData;
```

So the problem with this approach, you can also have "Called", you can have NoData + Loading at the same time, you can have Loading + Data at the same time.  
Those are all important and needed, Loading + Data can happen on a requery/fetch more.  Say I have an "infinite scroll" where I am just updating a "size" on the query, with the above, I would switch betewwn Loading and Data, when really I want both.

**Comment by jatsrt** [comment] 2018-03-27 12:29
And to be fair this works but is kind of ugly right now (for simplicity I am switching between loading and data):
```
<Query query=listingQuery>
        ...(
             response => {
               let parse = listingQuery##parse;
               response##loading |> Js.to_bool ?
                 "Loading" |> Util.ste :
                 (
                   switch (response##data |> Js.Nullable.toOption) {
                   | None => ReasonReact.nullElement
                   | Some(data) =>
                     let listing = parse(data)##listing;
                     <ListingEdit listing />;
                   }
                 );
             }
           )
      </Query>
```

**Comment by thangngoc89** [comment] 2018-03-27 12:55
We can use React terminology like prevState and nextState for handling loading and error of optimistic loading

**Comment by jatsrt** [comment] 2018-03-27 13:03
Another problem that I am not sure how to handle, Apollo Client does not return Some/None for data, it returns {} or {"has": "data"}

**Comment by jatsrt** [comment] 2018-03-27 13:07
OK @osener @grsabreu check out:
https://github.com/zenlist/bs-react-apollo/tree/shorter
This is not "complete" because of the above problem

**Comment by jatsrt** [comment] 2018-03-27 13:44
See https://github.com/zenlist/bs-react-apollo/blob/eb595ae9a509b17e6679a39177b3afd6b3770ec7/src/ReactApollo.re#L56
This should address Loading vs. LoadingWithData

**Comment by kgoggin** [comment] 2018-03-27 14:16
This is awesome! Really cool to see everyone jumping in.

I think the [network status field](https://www.apollographql.com/docs/react/api/react-apollo.html#graphql-query-data-networkStatus) could help guide how we handle loading states. I'd do something like:

```reason
type loading = | Loading | SetVariables | FetchMore | Refetch | Poll;
```
When dealing with the aggregate response type, I don't think you can get away from the fact that each of the three data points (loading, error, data) each have essentially a Some/None state, which leads to 3^2 = 9 possible states. While we could create a variant with constructors for all 9 possibilities, naming all those feels icky (`HasDataNoErrorNotLoading`?). What we if used a tuple:

```reason
type response = (option(loading), option(error), option(data));
```
I'll concede that pattern matching on this doesn't feel as "clean", but I think it more accurately reflects what we're dealing with here, which is 3 distinct values that operate more or less independently of each other, but which we want to deal with as a group. And, by making the loading type include all possible loading conditions, it enables as much flexibility as you'd ever want with handling the UI, but you could always just worry about `Some(_loading)` and not care exactly which flavor of loading you're dealing with.

I'd also envision writing a response helper to deal with the majority of cases where we show a spinner if loading, and error if there's an error, or the data, in that order so I didn't have to write the same pattern matching over and over - abstractions like that would be pretty easy to build on top of something like this, and would maybe even make sense to include in the lib (not 100% sure about that but worth considering).

Anyway those are my kind of ramble-y thoughts. Really excited to see this come together!

**Comment by jatsrt** [comment] 2018-03-27 15:18
ok without @kgoggin suggestions code approximately looks like:

```
<Query variables=listingQuery##variables>
        ...(
             ({data}) =>
               switch (data) {
               | Loading => <Loading />
               | Error(_error) => <Error error="Error" />
               | NoData => ReasonReact.nullElement
               | LoadingWithData(data)
               | Data(data) => <ListingEdit listing=data##listing />
               }
           )
      </Query>
```

**Comment by jatsrt** [comment] 2018-03-27 15:55
The "shorter" syntax is merged into develop at this point.  Please take a look, try it out and make any suggestions.  This is "working", though mutations are still not super clean, on an internal project, if anyone would like some sample code, let me know.

**Comment by thangngoc89** [comment] 2018-03-27 16:23
Well, instead of tuple of 3, you can use record because it could be consider as named tuple

**Comment by grsabreu** [comment] 2018-03-27 17:20
This thread is getting really exciting!

I really agree with @kgoggin points that naming all possible cases are hard. I think we can simplify the cases to the most used ones (Loading, Data, Error, NoData) and let still pass anyways the raw data as fallback if someone else needs more granularity.

the usual
```reason
<Query variables=listingQuery##variables>
        ...(
             ({data}) =>
               switch (data) 
```

the granular
```reason
<Query variables=listingQuery##variables>
        ...(
             ({ rawData, loading, error }) =>
               switch (rawData, loading, error) {
                   | (Some(data), true, Some(x))
                   etc
               } 
```

Because 90% of the cases you don't actually will try to render an error case with a data response, only when you are using the `refetch` or `fetchMore` probably.

I think that keeping the variant approach will make the code more readable and Reason-idiomatic for the lib consumer.

For the mutations I think we can do the same approach, I'm going to try to push a functor `CreateMutation` in the same idea as the `CreateQuery` today so I can have your opinion guys

**Comment by jatsrt** [comment] 2018-03-27 17:22
@grsabreu Take a look at the latest code from my repo, as I "started" the mutation code.  I'd suggest working from there and generate a PR, so we can keep the thoughts/code in one place.  I can keep testing new code/ideas on my larger internal project to see how they work.  

Also, feel free to modify the code to the approach you put above, makes sense to me.

**Comment by jatsrt** [comment] 2018-03-27 17:33
@grsabreu thoughts on the "raw" data being available, it might be worth still parsing it and returning it

Since it can be an empty object, the best way I can think of turning that into an option(Some/None) is:

```
switch (Config.parse(data)) {
        | parsedData => Some(parsedData)
        | exception _ => None
        }
```

**Comment by jatsrt** [comment] 2018-03-27 17:40
Updated code with this approach, needs more work

**Comment by grsabreu** [comment] 2018-03-27 20:14
oh yeah! I agree that it should be parsed by graphql_ppx too @jatsrt, I'm going to take a look soon in your WIP

**Comment by kgoggin** [comment] 2018-03-27 21:02
I'm about to play a game of devil's advocate here with a few things, but please don't read any negativity into it - I think everyone's got great ideas and I just want to hopefully helpfully push back on a few to keep the discussion moving towards a great final API 😉. 

Regarding the "rawData" idea: I don't love letting the library define what the "most used" cases are because I feel like that'll be different for everyone - I'd rather see it be as straightforward as possible to get at all cases and then someone can write abstractions to cover their own "most used" cases as needed.

That being said, if the majority of people feel like slimming down the possible cases makes the most sense, can we call it something other than `data`? Maybe `response` because its the aggregate of the whole response? And then you'd still have access to "raw" `data`, `error`, and `loading` directly from the JS response?

Also want to throw out again that `networkStatus` is just _begging_ to be parsed into a variant. No one wants to have to look up what those numbers mean! And then instead of a `bool`, the `loading` field becomes `option(loading)` - you can ignore the specific type if you don't care, but it's there if you do.

Regarding handling an empty object, I think you nailed that approach @jatsrt - just convert it to an option.

Okay, one last nit to pick: do we really need to do this as a functor? I think the reasoning is that you want access to the response type so you can properly type the `data`, right? We'd be able to get away from that if we didn't try to parse the JSON before returning it, just like it works in the current implementation. Or would it work to just do something like this?

```reason
  type response('parsedData) =
    | Loading
    | Error(apolloError)
    | Data('parsedData)
    | NoData;
```
I'm a little fuzzy with type arguments so maybe there's a reason not to do that. But then I still think you'd want to weigh the pros/cons of the functor pattern against just asking the consumer to parse the query before using it. As someone who was new to Reason just a few months ago, the functor pattern definitely threw me for a loop at first and compared to just being able to use a `<Query>` component wherever you need it, it feels a little heavy.

Hope that's helpful. Again, great work everyone!

**Comment by osener** [comment] 2018-03-27 21:18
If you'd prefer not to go the tuple route while slimming down variants and making it easy to ignore the less common states, another option could be something like

```reason
type queryState =
  | Loading(option(Js.Json.t))
  | Error(apolloError, option(Js.Json.t))
  | Data(Js.Json.t)
  | NoData;
```
or maybe
```reason
type queryState =
  | Loading(option(Js.Json.t))
  | Error(apolloError, option(Js.Json.t))
  | Done(option(Js.Json.t));
```

**Comment by jatsrt** [comment] 2018-03-28 01:07
@kgoggin Great stuff, thanks for being so thoughtful on this.

I like the "rawData" thought you had, were data, error, loading, called, etc are as "pure" as they can be.  Still parsed, but as close to the original as possible.  Then calling the "reasoned" response something else.  I think slimming it down for "basic" use cases makes sense and can make adoption a bit easier.  Though I personally probably would not use them.  I like the tuple idea, as there are many variations.

Agree with network status, I put in code to map them, just didn't do it yet.  No reason in reason to return ints.

Re the "empty" object, is anyone else out there smarter than me in how to match Js.Json.t = {}.  The best I can manage is failing on the parse, seems inefficient.

So, now the functor, personally I am very new to Reason, like < 1 month.  But I am not new to functors or functional languages.  I personally like the approach and gives some great type definition help.  I don't know the language well enough yet to know the intricacies of it's type definitions.

**Comment by jatsrt** [comment] 2018-03-28 01:09
@osener I tried that approach, but it's not just "data", could be other items as well.  So, it's hard to determine the stopping point, I think the tuple approach, a simple variant approach, both with good examples/documentation would work best.

**Comment by jatsrt** [comment] 2018-03-28 01:15
@grsabreu I just realized I did the "rawData" example on mutation not query.
 I'll reiterate here too, I like @kgoggin 's recommendation that data, loading, error, etc stay "pure", and use something like result for the Loading, Data, NoData, Error result

Thoughts?

**Comment by grsabreu** [comment] 2018-03-29 03:24
@jatsrt, how that would be?
Something like
```reason
<Query variables=listingQuery##variables>
        ...(
             ({ result, data, loading, error }) =>
          /* Where result are the common possible states (the variant approach), but we leave data (Also parsed as option(Query.t), loading as bool, and error as Some(apolloError)) if the user wants more granularity */
               switch (rawData, loading, error) {
                   | (Some(data), true, Some(x))
                   etc
               } 
```

something like that?

**Comment by kgoggin** [comment] 2018-03-29 20:24
Ah, so I missed the example usage in @jatsrt's repo where the functor allows you to just pass the result of the graphql_ppx macro. That makes sense - I'm actually not using graphql_ppx and rolling my own parsing because I wanted to reuse my types everywhere and because I wanted to use inline fragments. But I can see how it makes everything cleaner to do it that way.

**Comment by jatsrt** [comment] 2018-04-01 02:20
@grsabreu any luck?

**Comment by grsabreu** [comment] 2018-04-01 03:58
Oh yeah @kgoggin! I had that in mind also.

So everyone agrees with `result` being a variant with the four common states and them we leave `raw`, `loading` and `error` if the user needs more granularity?

I think we just need to now make the Mutation a functor also and we're done.
Gonna try to implement it tomorrow to get your review

**Comment by jatsrt** [comment] 2018-04-02 13:35
@grsabreu Yes I think we are all in agreement.  My code base has the mutation as a functor now, but probably needs a bit of a cleanup.  I have an internal project fully using both query and mutation as functors right now, works great!

**Comment by grsabreu** [comment] 2018-04-02 14:13
awesome! @jatsrt I also tested the functors in an internal project I'm working and they are all going good also

**Comment by grsabreu** [comment] 2018-04-02 14:15
I saw your mutation code and it seems good to me.
I think we can send a PR now to reason-apollo, let us know your thoughts @Gregoirevda

**Comment by kgoggin** [comment] 2018-04-02 14:40
My only suggestion would be to do `result`, `loading`, `error`, and `data` to keep things consistent with the underlying API. Other than that I think this makes sense to me!

**Comment by guilhermedecampo** [comment] 2018-04-07 03:16
This thread is awesome. PR is on the way?

**Comment by Gregoirevda** [comment] 2018-04-07 17:35
A PR would be welcome! I'll otherwise make one this week!

**Comment by jatsrt** [comment] 2018-04-09 19:29
So, I think the code still needs a bit of refactor to fully implement the (result, loading, data, error) standard.  I will try to clean that up in the next day or so as there's no PR for this.  I also will need to fork this project and get the code into the fork, as when I started this I did it as a new clean project since I didn't know how people would react.  Much better to get it here and supported going forward.

**Comment by Gregoirevda** [comment] 2018-04-11 23:27
PR is on it's way: https://github.com/apollographql/reason-apollo/tree/feature/react-apollo-2.1

**Comment by idkjs** [comment] 2018-04-12 14:01
@jatsrt offer still open for that sample code you mentioned up thread?

**Comment by idkjs** [comment] 2018-04-12 15:31
@jatsrt generally, I'm curious about the difference between what we are doing here and how @kgoggin is doing it without using ppx as pointed out in his [blog post](https://www.kylegoggin.com/sharing-types-in-a-reasonml-graphql-app/). Sharing types seems to be a good thing to know about.

Specifically, I am about to go through this [zenlist repo fork](https://github.com/idkjs/bs-react-apollo) commit x commit to see how you thought through that. I am super grateful for your offer to guide me a bit. When I come across something, ping you in a comment?

**Comment by jatsrt** [comment] 2018-04-12 17:03
I'll have to read @kgoggin 's article more closely to determine the advantage over just using @bsRecord.

**Comment by kgoggin** [comment] 2018-04-12 19:42
@idkjs happy to weigh in as well! My issue with graphql_ppx (even when using `@bsRecord`) is that the type it generates is tied directly to the query you're making. If you make a second query against the same GQL type elsewhere in your app, but request different fields, the auto-generated type is different.

Fortunately reason-apollo doesn't actually depend on it at all - in neither its current or proposed future form being discussed here! All it wants is a `string` passed as the `query` prop. Whether that string comes from graphql_ppx or you write it yourself, it'll make no difference. _But_, if you do leave out graphql_ppx, you'll also have to parse the JSON result you get back from Apollo into the types you've defined, which is the bulk of my post.

All that said, if you don't care about reusing your types or are just getting started, graphql_ppx is awesome! And, reason-apollo should support either using graphql_ppx or not - whatever makes more sense for you and what you're doing. Hope that helps clarify a little.

**Comment by Gregoirevda** [comment] 2018-04-12 22:31
@jatsrt the PR will contain updated code examples.
@kgoggin the module graphql_ppx gives back is a minimum required data structure you need to provide, so writing it manually is also an option.

**Comment by Gregoirevda** [comment] 2018-04-16 23:52
I updated the Query functor to give back `result`, `loading`, `error`, and `data`.
Mutation functor should take the same approach: variant for simple use cases and exposed parsed response from react-apollo for better granularity.

It currently looks like:
```
 type response =
      | Loading
      | LoadingWithData(Config.t)
      | Called
      | CalledWithData(Config.t)
      | Error(apolloError)
      | Data(Config.t)
      | NoData;
```
But wondering if it should be this variant (`result`), with rawData alongside (`loading`, `error`, and `data`). 
```
 type result =
      | Loading
      | Data(Config.t)
      | Error(apolloError)
      | Called;
```

**Comment by jatsrt** [comment] 2018-04-17 23:50
@Gregoirevda the loading/loadingwithdata was a hack, feel free to remove.  I'd say make it consistent and use the approach you laid out:

```
 type result =
      | Loading
      | Data(Config.t)
      | Error(apolloError)
      | Called;
```

**Comment by jatsrt** [comment] 2018-04-20 02:04
@Gregoirevda The only thing I see is that Query uses result/data and Mutation is using data/rawData, not sure what the best convention is, but probably should be consistent between the two?

**Comment by idkjs** [comment] 2018-04-20 12:29
FYI the swapi example on feature/2.1 branch, endpoint needs cors.

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.graph.cool/simple/v1/cjdgba1jw4ggk0185ig4bhpsn. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
```

**Comment by idkjs** [comment] 2018-04-21 16:54
I'm testing `reason-apollo@beta` and getting a type error when Im trying to pass the returned data to a component. Apparently, bs-platform 3.0 doesnt make a distinction between Js.boolean and bool types while ReasonApollo.response is returning a Js.boolean type, when i pass the parsed result to another component, that component assumes the type is bool which results in a type error. Fully explained in [reason.chat](https://reasonml.chat/t/bool-vs-js-boolean-in-reasonreact/506/6).[demo/reproduction](https://github.com/idkjs/react-crud-db).

This doesn't work.[src/Feedpage.re](https://github.com/idkjs/react-crud-db/blob/4fab96f8cff1a2aa141c9dc3f4edcf2328e4d4d3/src/components/FeedPage.re#L75)
```sh
This has type:
    array(Js.t(({.. id: string, isPublished: bool, text: string,
                  title: string}
                as 'a))) =>
    array(ReasonReact.reactElement)
  But somewhere wanted:
    Js.Array.t({. "id": string, "isPublished": Js.boolean, "text": string,
                 "title": string}) =>
    'b

  The incompatible parts:
    array(Js.t('a))
    vs
    Js.Array.t({. "id": string, "isPublished": Js.boolean, "text": string,
                 "title": string})
      (defined as
      array({. "id": string, "isPublished": Js.boolean, "text": string,
              "title": string}))
    at <anonymous> isPublished are incompatible
```

While the uncommented code just above it does.
```
response##feed
                   |> Array.mapi((index, post) =>
                        <div key=(index |> string_of_int)>
                          (post##title |> ste)
                        </div>
                      )
                   |> ReasonReact.arrayToElement
```

As suggested on reason.chat, does this have anything to do with this repo using bs-platform < 3.0?

**Comment by Gregoirevda** [comment] 2018-04-21 17:25
new beta version has been deployed on npm (0.7.1-beta) with among others:
- consistant render props (@jatsrt )
- webpack-dev-server in swapi example (@idkjs, I mentioned python simple server in PR, but this had to be added anyway)
- the result property as a variant (@kgoggin )
- `refetchQueries` fixes and `mutation` reason signature (@grsabreu )

@idkjs please add your in a new issue.

**Comment by grsabreu** [comment] 2018-04-21 18:04
Awesome @Gregoirevda, I'm going to try it out soon

**Comment by idkjs** [comment] 2018-04-21 21:01
Seems like `Utils.re` is common practice in the community for helper scripts. The beta has a `Utils.re` in it so if you add this to a project with your own `Utils.re` you get a module name collision. Just an FYI on user experience.

**Comment by idkjs** [comment] 2018-04-24 07:51
> @kgoggin those are totally valid points, tho I think the functor helps abstract the code to a cleaner and more simple approach to the consumer, a beginner would have less steps to do before hooking up the data with the component and also be more in contact with good practices from OCaml. I think that it is for the best if we stick with the functor approach.

I'm still a beginner or an idiot given how long i have been at this, and I just ran into this issue. I'm rereading this to figure out how to get rawdata without a ReasonReact.element. I even posted an [issue](https://github.com/apollographql/reason-apollo/issues/71) on this very repo, yesterday. 

Anyone mind showing how to use the rawData result only? Something like this that works maybe?
```
module GetAllPersons = [%graphql
  {|
    query getAllPersons {
      allPersons {
        id
        age
        name
      }
    }
|}
];

module GetAllPersonsQuery = ReasonApollo.CreateQuery(GetAllPersons);

module QueryResults = GetAllPersonsQuery.result; // how do we get the data only off the functor?
let () = print_endline(QueryResults....)
```

Thank you.

**Comment by idkjs** [comment] 2018-04-24 12:39
another example of reason-apollo@beta. https://github.com/idkjs/reasonapollo-crud-db

**Comment by Gregoirevda** [comment] 2018-04-24 13:56
@idkjs nice example! I'll reply on the other issue

**Comment by Gregoirevda** [comment] 2018-05-01 19:28
Published and merged on master

**Closed by Gregoirevda** 2018-05-01 19:28 UTC

**Comment by idkjs** [comment] 2018-05-02 09:57
@Gregoirevda just made my day, man. Thanks.
